spring:
 datasource:
   url: jdbc:mysql://localhost:3306/projectdb?createDatabaseIfNotExist=true
   username: root
   password: test123
   driver-class-name: com.mysql.jdbc.Driver 


 mvc:
   view:
     prefix: /WEB-INF/jsps/
     suffix: .jsp



